config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "main#home"
  resources :model_shoes

  resources :shoes, only: [:index, :show]

  resources :companies

  resources :categories, only: [:index, :show]

  resources :comments

  namespace :admin do
    root to: "shoes#index"  
    resources :shoes
    resources :categories
  end 

end

app/models/model_shoe.rb
class ModelShoe < ActiveRecord::Base
	has_many :shoes
end

app/controllers/model_shoes_controller.rb
class ModelShoesController < ApplicationController
  before_action :set_model_shoe, only: [:show, :edit, :update, :destroy]

  # GET /model_shoes
  # GET /model_shoes.json
  def index
    @model_shoes = ModelShoe.all
  end

  # GET /model_shoes/1
  # GET /model_shoes/1.json
  def show
  end

  # GET /model_shoes/new
  def new
    @model_shoe = ModelShoe.new
  end

  # GET /model_shoes/1/edit
  def edit
  end

  # POST /model_shoes
  # POST /model_shoes.json
  def create
    @model_shoe = ModelShoe.new(model_shoe_params)

    respond_to do |format|
      if @model_shoe.save
        format.html { redirect_to @model_shoe, notice: 'Model shoe was successfully created.' }
        format.json { render :show, status: :created, location: @model_shoe }
      else
        format.html { render :new }
        format.json { render json: @model_shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /model_shoes/1
  # PATCH/PUT /model_shoes/1.json
  def update
    respond_to do |format|
      if @model_shoe.update(model_shoe_params)
        format.html { redirect_to @model_shoe, notice: 'Model shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @model_shoe }
      else
        format.html { render :edit }
        format.json { render json: @model_shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /model_shoes/1
  # DELETE /model_shoes/1.json
  def destroy
    @model_shoe.destroy
    respond_to do |format|
      format.html { redirect_to model_shoes_url, notice: 'Model shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model_shoe
      @model_shoe = ModelShoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_shoe_params
      params.require(:model_shoe).permit(:shoe_id)
    end
end

app/helpers/model_shoes_helper.rb
module ModelShoesHelper
end

app/views/model_shoes/_form.html.erb
<%= form_for(@model_shoe) do |f| %>
  <% if @model_shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model_shoe.errors.count, "error") %> prohibited this model_shoe from being saved:</h2>

      <ul>
      <% @model_shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shoe_id %><br>
    <%= f.number_field :shoe_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/model_shoes/edit.html.erb
<h1>Editing model_shoe</h1>

<%= render 'form' %>

<%= link_to 'Show', @model_shoe %> |
<%= link_to 'Back', model_shoes_path %>

app/views/model_shoes/index.html.erb
<h1>Listing model_shoes</h1>

<table>
  <thead>
    <tr>
      <th>Shoe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @model_shoes.each do |model_shoe| %>
      <tr>
        <td><%= model_shoe.shoe_id %></td>
        <td><%= link_to 'Show', model_shoe %></td>
        <td><%= link_to 'Edit', edit_model_shoe_path(model_shoe) %></td>
        <td><%= link_to 'Destroy', model_shoe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model shoe', new_model_shoe_path %>

app/views/model_shoes/new.html.erb
<h1>New model_shoe</h1>

<%= render 'form' %>

<%= link_to 'Back', model_shoes_path %>

app/views/model_shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shoe:</strong>
  <%= @model_shoe.shoe_id %>
</p>

<%= link_to 'Edit', edit_model_shoe_path(@model_shoe) %> |
<%= link_to 'Back', model_shoes_path %>