config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "main#home"
  resources :model_shoes

  resources :shoes, only: [:index, :show]

  resources :companies

  resources :categories, only: [:index, :show]

  resources :comments

  namespace :admin do
    root to: "shoes#index"  
    resources :shoes
    resources :categories
  end 

end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
	acts_as_commentable
	belongs_to :category
	belongs_to :company
	validates :name, presence: true
  	validates :description, presence: true
  	validates :price, presence: true
  	validates_numericality_of :price, greater_than: 0
  	has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/system/shoes/covers/default/:style/missing.jpg"
  	validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
  	scope :avaiable, ->{where("LENGTH(name) > 3")}
end

app/controllers/admin/shoes_controller.rb
class Admin::ShoesController < Admin::AdminController
	before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
    @categories = Category.active
    @company = Company.all
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    Rails.logger.info "[create shoe from admin], #{params.inspect}"
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to admin_shoes_url(@shoe), notice: 'Shoe was successfully created.' }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to admin_shoes_url(@shoe), notice: 'Shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to admin_shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:name, :category_id, :company_id, :description, :price, :cover)
    end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show]

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
    @new_comment = Comment.new
    @comments = @shoe.comments.order("updated_at DESC")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:name, :category_id, :company_id, :description, :price)
    end
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/admin/shoes/_form.html.erb
<%= form_for @shoe, :url => admin_shoes_path, :html => { :multipart => true } do |f| %>
  <% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% @shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= select(:shoe, :category_id, options_from_collection_for_select(@categories, :id, :name)) %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= select(:shoe, :company_id, options_from_collection_for_select(@companies, :id, :name)) %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.file_field :cover %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/shoes/edit.html.erb
<h1>Editing shoe</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_shoe_path(@shoe) %> |
<%= link_to 'Back', admin_shoes_path %>

app/views/admin/shoes/index.html.erb
<h1>Listing shoes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Company</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoes.each do |shoe| %>
      <tr>
        <td><%= shoe.name %></td>
        <td><%= shoe.category_id %></td>
        <td><%= shoe.company_id %></td>
        <td><%= shoe.description %></td>
        <td><%= shoe.price %></td>
        <td><%= link_to 'Show', admin_shoe_path(shoe) %></td>
        <td><%= link_to 'Edit', edit_admin_shoe_path(shoe) %></td>
        <td><%= link_to 'Destroy', admin_shoe_path(shoe), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shoe', new_admin_shoe_path %>

app/views/admin/shoes/new.html.erb
<h1>New shoe</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_shoes_path %>

app/views/admin/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @shoe.cover.url(:medium) %>
</p>
<p>
  <strong>Name:</strong>
  <%= @shoe.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @shoe.category_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @shoe.company_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shoe.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @shoe.price %>
</p>

<%= link_to 'Edit', edit_admin_shoe_path(@shoe) %> |
<%= link_to 'Back', admin_shoes_path %>